[bazel] Fix skia_app_container macro after upgrading to Bazel 6.0.0.
After upgrading to Bazel 6.0.0 the skia_app_container macro broke with the following error:

    ERROR: .../external/rules_pkg/BUILD:38:10: in py_binary rule @rules_pkg//:build_tar: The Python toolchain does not provide a runtime for Python version PY2

Here is the rules_pkg version downloaded by Bazel:

    $ cat $(bazel info output_base)/external/rules_pkg/version.bzl
    ...
    version = "0.2.6"

This should actually be 0.4.0, as per our //WORKSPACE file: https://skia.googlesource.com/buildbot/+/3aac2c7ee4a83eb9493aa8b02c8fcbb4c13d5d8d/WORKSPACE#289.

This discrepancy can probably be explained because some code earlier in the //WORKSPACE file might be downloading the older version of rules_pkg. Likely culprits:

- https://skia.googlesource.com/buildbot/+/3aac2c7ee4a83eb9493aa8b02c8fcbb4c13d5d8d/WORKSPACE#271

- https://skia.googlesource.com/buildbot/+/3aac2c7ee4a83eb9493aa8b02c8fcbb4c13d5d8d/WORKSPACE#279

As expected, rules_pkg version 0.2.6 depends on Python 2: https://github.com/bazelbuild/rules_pkg/blob/0.2.6/pkg/BUILD#L34C28-L34C28. Fortunately this is no longer the case in rules_pkg version 0.4.0, which is what we have in our WORKSPACE file.

The fix is to move the rules_pkg declaration earlier in the WORKSPACE file so it takes precedence over the rules_pkg version presumably installed by the aforementioned potential culprits.

Bug: b/314309650
Change-Id: I85019b884874161a145421cd23c867267e7b0cb6
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/785234
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Eric Boren <borenet@google.com>