[bazel] bazel_build_all.go: Stop invoking Bazel with --remote_download_minimal flag.
For some reason, said flag causes errors such as the following under Bazel 6:

    ERROR: /mnt/pd0/s/w/ir/repo/perf/go/ingest/process/BUILD.bazel:29:8: GoCompilePkg perf/go/ingest/process/process_test.internal.a failed: I/O exception during sandboxed execution: 249 errors during bulk transfer:
    java.io.FileNotFoundException: /dev/shm/bazel_cache/336ea3039fed6f3e5316998662c62b7f/execroot/skia_infra/bazel-out/k8-fastbuild-ST-8f6eb6207b9d/bin/external/io_bazel_rules_go/stdlib_/pkg/include/funcdata.h (No such file or directory)
    java.io.FileNotFoundException: /dev/shm/bazel_cache/336ea3039fed6f3e5316998662c62b7f/execroot/skia_infra/bazel-out/k8-fastbuild-ST-8f6eb6207b9d/bin/external/io_bazel_rules_go/stdlib_/pkg/include/asm_ppc64x.h (No such file or directory)
    java.io.FileNotFoundException: /dev/shm/bazel_cache/336ea3039fed6f3e5316998662c62b7f/execroot/skia_infra/bazel-out/k8-fastbuild-ST-8f6eb6207b9d/bin/external/io_bazel_rules_go/stdlib_/pkg/linux_amd64/container/list.a (No such file or directory)
    ...

Another reason for deleting this flag is that it apparently doesn't speed up our build times by much, as we learned after deleting --remote_download_minimal from bazel_test_all.go in https://skia-review.googlesource.com/c/buildbot/+/544216.

Bug: skia:13293
Change-Id: Ifd7f63c035bf13df6b8829263f5cc3bde29b13b7
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/545496
Reviewed-by: Joe Gregorio <jcgregorio@google.com>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>