[infra] Run RBE using the VM service account, not JSON keys.
I ran into authentication errors when trying to get our Bazel
builds to use Remote Build Execution working. To get the bazel
commands to use the service account connected to the VM (which
for us was not the default service account, but chromium-swarm-bots@
skia-swarming-bots.iam.gserviceaccount.com), I added
--google_default_credentials.

In our skia-infra-rbe project, which is where the RBE connections
are targeting, I had granted the chromium-swarm-bots service account
the permissions of Remote Build Execution Action Cache Writer and
Remote Build Execution Artifact Creator.

However, I was getting a mysterious error when running bazel build:
ERROR: Failed to query remote execution capabilities: PERMISSION_DENIED: Request had insufficient authentication scopes

As mentioned on https://cloud.google.com/remote-build-execution/docs/authentication?hl=en#service_accounts_on_compute_engine
The VMs scopes needed to be "https://www.googleapis.com/auth/cloud-platform",
essentially "all Google Cloud APIs". The ones on our Swarming
machines were just GCS + Email + PubSub.

I made use of //scripts/add_gce_scopes to add the appropriate scope
to skia-e-gce-300 to skia-e-gce-320 (the machines that bazel+RBE
target) and updated the go/gce/swarming code to automatically include
that scope when we re-create the instances.

Change-Id: Ic5c90f2821fe0b85cb1a093d09f50f36e423c64d
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/446297
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>